# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sx_store', '0002_remove_goodsvalue_gtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsvalue',
            name='gtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sx_store.ArticleCategory'),
            preserve_default=False,
        ),
    ]
